---
title: "simResults_backward"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(autoCovariateSelection)
require(dplyr)
require(cobalt)
require(WeightIt)
library(tidyverse)
library(ggplot2)
library(lmtest)
library(MASS)
library(Boruta)
library(GA)
library(mclust)
library(penalizedSVM)
library(xgboost)
library(caret)
require(autoCovariateSelection)
library(randomForest)
require(lmtest)
```

```{r load basic information, warning=FALSE, cache=TRUE}
# global information
exposure <- "obese"
outcome <- "diabetes" 
investigator.specified.covariates <- 
  c(# Demographic
    "age.cat", "sex", "education", "race", 
    "marital", "income", "born", "year",
    
    # health history related variables/access
    "diabetes.family.history", "medical.access",
    
    # behavioral
    "smoking", "diet.healthy", "physical.activity", "sleep",
    
    # Laboratory 
    "uric.acid", "protein.total", "bilirubin.total", "phosphorus",
    "sodium", "potassium", "globulin", "calcium.total", 
    "systolicBP", "diastolicBP", "high.cholesterol"
  )
covform <- paste0(investigator.specified.covariates, collapse = "+")
out.formula <- as.formula(paste0("outcome", "~", "exposure"))

url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenario/data_1.rds")
data <- readRDS(url(url))
proxy.list <- names(data[, c(grep("^rec", names(data), value = TRUE))])
covarsTfull <- c(investigator.specified.covariates, proxy.list)
Y.form <- as.formula(paste0(c("outcome~exposure", 
                              covarsTfull), collapse = "+") )

initial.formula <- as.formula(paste0("outcome~exposure+",
                                     covform,
                                     collapse = "+"))
full.formula <- as.formula(paste0("outcome~exposure+",
                                  paste0(covarsTfull, collapse = "+"),
                                  collapse = "+"))
```

```{r initialization before for-loop, warning=FALSE, cache=TRUE}
# 'a' ranges from 1 to 1000 to change the number of datasets loaded in each for-loop
a <- 1000

RD_backward <- data.frame(RD = numeric(), SE = numeric())

num.proxy_backward <- c()
```

```{r scenario: for-loop generating RD & SE results for backward, warning=FALSE, cache=TRUE}
set.seed(42)

# Folder "scenario"
for (i in 1:a) {
  closeAllConnections()
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenario/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))
  
  # found some id != idx
  data$idx <- data$id
  
  initial.model <- glm(initial.formula, data = data, family = binomial)
  full.model <- glm(full.formula, data = data, family = binomial)
  stepwise_backward <- stepAIC(full.model, 
                              scope = list(lower = initial.model, 
                                           upper = full.model), 
                              direction = "backward")
  
  sel.variables <- all.vars(formula(stepwise_backward))[-1]
  proxy_backward <- proxy.list[proxy.list %in% sel.variables]
  proxyform <- paste0(proxy_backward, collapse = "+")
  rhsform <- paste0(c(covform, proxyform), collapse = "+")
  ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
  W.out_backward <- weightit(ps.formula, 
                          data = data, 
                          estimand = "ATE",
                          method = "ps")
  #
  data$ps.l <- W.out_backward$ps
  data$w.l <- W.out_backward$weights
  
  fit.OR_backward <- glm(out.formula,
                      data = data,
                      weights = W.out_backward$weights,
                      family= binomial(link = "logit"))
  fit.RD_backward <- glm(out.formula,
                       data = data,
                       weights = W.out_backward$weights,
                       family = gaussian(link= "identity"))
  sum.RD_backward <- c(summary(fit.RD_backward)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_backward)[2,2]))
  
  RD_backward[i,] <- sum.RD_backward
  rownames(RD_backward)[i] <- paste0("data.", i, "_backward")
  num.proxy_backward <- c(num.proxy_backward, length(proxy_backward))
  names(num.proxy_backward)[i] <- paste0("data.", i, "_backward")
  
  proxy_backward.i <- paste0("proxy_backward.", i)
  assign(proxy_backward.i, proxy_backward)
  num.proxy_backward.i <- paste0("num.proxy_backward.", i)
  assign(num.proxy_backward.i, length(proxy_backward))
  sum.RD_backward.i <- paste0("sum.RD_backward.", i)
  assign(sum.RD_backward.i, sum.RD_backward)
}
```

```{r scenarioER: for-loop generating RD & SE results for backward, warning=FALSE, cache=TRUE}
set.seed(42)

# Folder "scenarioER"
for (i in 1:a) {
  closeAllConnections()
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioER/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))
  
  # found some id != idx
  data$idx <- data$id
  
  initial.model <- glm(initial.formula, data = data, family = binomial)
  full.model <- glm(full.formula, data = data, family = binomial)
  stepwise_backward <- stepAIC(full.formula, 
                              scope = list(lower = initial.model, 
                                           upper = full.model), 
                              direction = "backward")

  sel.variables <- all.vars(formula(stepwise_backward))[-1]
  proxy_backward <- proxy.list[proxy.list %in% sel.variables]
  proxyform <- paste0(proxy_backward, collapse = "+")
  rhsform <- paste0(c(covform, proxyform), collapse = "+")
  ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
  W.out_backward <- weightit(ps.formula, 
                          data = data, 
                          estimand = "ATE",
                          method = "ps")
  #
  data$ps.l <- W.out_backward$ps
  data$w.l <- W.out_backward$weights
  
  fit.OR_backward <- glm(out.formula,
                      data = data,
                      weights = W.out_backward$weights,
                      family= binomial(link = "logit"))
  fit.RD_backward <- glm(out.formula,
                       data = data,
                       weights = W.out_backward$weights,
                       family = gaussian(link= "identity"))
  sum.RD_backward <- c(summary(fit.RD_backward)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_backward)[2,2]))
  
  RD_backward[i+a,] <- sum.RD_backward
  rownames(RD_backward)[i+a] <- paste0("ER.data.", i, "_backward")
  num.proxy_backward <- c(num.proxy_backward, length(proxy_backward))
  names(num.proxy_backward)[i+a] <- paste0("ER.data.", i, "_backward")
  
  proxy_backward.i <- paste0("proxy_backward.ER.", i)
  assign(proxy_backward.i, proxy_backward)
  num.proxy_backward.i <- paste0("num.proxy_backward.ER.", i)
  assign(num.proxy_backward.i, length(proxy_backward))
  sum.RD_backward.i <- paste0("sum.RD_backward.ER.", i)
  assign(sum.RD_backward.i, sum.RD_backward)
}
```

```{r scenarioOR: for-loop generating RD & SE results for backward, warning=FALSE, cache=TRUE}
set.seed(42)

# Folder "scenarioOR"
for (i in 1:a) {
  closeAllConnections()
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioOR/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))
  
  # found some id != idx
  data$idx <- data$id
  
  initial.model <- glm(initial.formula, data = data, family = binomial)
  full.model <- glm(full.formula, data = data, family = binomial)
  stepwise_backward <- stepAIC(full.formula, 
                              scope = list(lower = initial.model, 
                                           upper = full.model), 
                              direction = "backward")

  sel.variables <- all.vars(formula(stepwise_backward))[-1]
  proxy_backward <- proxy.list[proxy.list %in% sel.variables]
  proxyform <- paste0(proxy_backward, collapse = "+")
  rhsform <- paste0(c(covform, proxyform), collapse = "+")
  ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
  W.out_backward <- weightit(ps.formula, 
                          data = data, 
                          estimand = "ATE",
                          method = "ps")
  #
  data$ps.l <- W.out_backward$ps
  data$w.l <- W.out_backward$weights
  
  fit.OR_backward <- glm(out.formula,
                      data = data,
                      weights = W.out_backward$weights,
                      family= binomial(link = "logit"))
  fit.RD_backward <- glm(out.formula,
                       data = data,
                       weights = W.out_backward$weights,
                       family = gaussian(link= "identity"))
  sum.RD_backward <- c(summary(fit.RD_backward)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_backward)[2,2]))
  
  RD_backward[i+2*a,] <- sum.RD_backward
  rownames(RD_backward)[i+2*a] <- paste0("OR.data.", i, "_backward")
  num.proxy_backward <- c(num.proxy_backward, length(proxy_backward))
  names(num.proxy_backward)[i+2*a] <- paste0("OR.data.", i, "_backward")
  
  proxy_backward.i <- paste0("proxy_backward.OR.", i)
  assign(proxy_backward.i, proxy_backward)
  num.proxy_backward.i <- paste0("num.proxy_backward.OR.", i)
  assign(num.proxy_backward.i, length(proxy_backward))
  sum.RD_backward.i <- paste0("sum.RD_backward.OR.", i)
  assign(sum.RD_backward.i, sum.RD_backward)
}
```


```{r read RD & SE results by backward, warning=FALSE, cache=TRUE}
RD_backward
```


```{r check number of proxies selected, warning=FALSE, cache=TRUE}
num.proxy_backward
mean(num.proxy_backward[complete.cases(num.proxy_backward)])
```

```{r check intermediate results for each data by backward, warning=FALSE, cache=TRUE}
# check RD & SE by backward for each data, print:
#   sum.RD_backward.n, sum.RD_backward.ER.n, or sum.RD_backward.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
sum.RD_backward.1
sum.RD_backward.ER.2

# check proxy selected by backward for each data, print:
#   proxy_backward.n, proxy_backward.ER.n, or proxy_backward.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
proxy_backward.1
proxy_backward.ER.3

# check number of proxy selected by backward for each data, print:
#   num.proxy_backward.n, num.proxy_backward.ER.n, or num.proxy_backward.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
num.proxy_backward.1
num.proxy_backward.OR.3
```
