---
title: "simResults_svm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(autoCovariateSelection)
require(dplyr)
require(cobalt)
require(WeightIt)
library(tidyverse)
library(ggplot2)
library(lmtest)
library(MASS)
library(Boruta)
library(GA)
library(mclust)
library(penalizedSVM)
library(xgboost)
library(caret)
require(autoCovariateSelection)
library(randomForest)
require(lmtest)
```

```{r load basic information, warning=FALSE, cache=TRUE}
# global information
exposure <- "obese"
outcome <- "diabetes" 
investigator.specified.covariates <- 
  c(# Demographic
    "age.cat", "sex", "education", "race", 
    "marital", "income", "born", "year",
    
    # health history related variables/access
    "diabetes.family.history", "medical.access",
    
    # behavioral
    "smoking", "diet.healthy", "physical.activity", "sleep",
    
    # Laboratory 
    "uric.acid", "protein.total", "bilirubin.total", "phosphorus",
    "sodium", "potassium", "globulin", "calcium.total", 
    "systolicBP", "diastolicBP", "high.cholesterol"
  )
covform <- paste0(investigator.specified.covariates, collapse = "+")
out.formula <- as.formula(paste0("outcome", "~", "exposure"))

url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenario/data_1.rds")
data <- readRDS(url(url))
proxy.list <- names(data[, c(grep("^rec", names(data), value = TRUE))])
covarsTfull <- c(investigator.specified.covariates, proxy.list)
Y.form <- as.formula(paste0(c("outcome~ exposure", 
                              covarsTfull), collapse = "+") )
```

```{r initialization before for-loop, warning=FALSE, cache=TRUE}
# 'a' ranges from 1 to 1000 to change the number of datasets loaded in each for-loop
a <- 1000

RD_svm <- data.frame(RD = numeric(), SE = numeric())

num.proxy_svm <- c()
```

```{r scenario: for-loop generating RD & SE results for svm, warning=FALSE, cache=TRUE}
set.seed(42)

# Folder "scenario"
for (i in 1:a) {
  closeAllConnections()
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenario/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))

  # found some id != idx
  data$idx <- data$id
  covar.mat <- model.matrix(Y.form, data = data)[,-1]
  
  svmTrainOutcome <- data$outcome
  svmTrainOutcome[svmTrainOutcome == 0] <- -1
  svmTrainPreds <- data.frame(covar.mat)
  
  bounds <- t(data.frame(log2lambda1=c(-10, 10), log2lambda2=c(-10,10)))
  colnames(bounds)<-c("lower", "upper")
  svm.model <- svmfs(x=covar.mat,
                     y = svmTrainOutcome,
                     fs.method = "scad+L2",
                     bounds=bounds,
                     grid.search = "interval",
                     inner.val.method = "cv",
                     show = "none",
                     parms.coding = "none",
                     seed=42)
  
  sel.variables <- colnames(covar.mat)[svm.model$model$fit.info$model.list$model$xind]
  proxy_svm <- proxy.list[proxy.list %in% sel.variables]
  proxyform <- paste0(proxy_svm, collapse = "+")
  rhsform <- paste0(c(covform, proxyform), collapse = "+")
  ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
  W.out_svm <- weightit(ps.formula, 
                          data = data, 
                          estimand = "ATE",
                          method = "ps")  
  
  data$ps.l <- W.out_svm$ps
  data$w.l <- W.out_svm$weights
  
  fit.OR_svm <- glm(out.formula,
                      data = data,
                      weights = W.out_svm$weights,
                      family= binomial(link = "logit"))
  fit.RD_svm <- glm(out.formula,
                       data = data,
                       weights = W.out_svm$weights,
                       family = gaussian(link= "identity"))
  sum.RD_svm <- c(summary(fit.RD_svm)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_svm)[2,2]))
  
  RD_svm[i,] <- sum.RD_svm
  rownames(RD_svm)[i] <- paste0("data.", i, "_svm")
  num.proxy_svm <- c(num.proxy_svm, length(proxy_svm))
  names(num.proxy_svm)[i] <- paste0("data.", i, "_svm")
  
  proxy_svm.i <- paste0("proxy_svm.", i)
  assign(proxy_svm.i, proxy_svm)
  num.proxy_svm.i <- paste0("num.proxy_svm.", i)
  assign(num.proxy_svm.i, length(proxy_svm))
  sum.RD_svm.i <- paste0("sum.RD_svm.", i)
  assign(sum.RD_svm.i, sum.RD_svm)
}
```

```{r scenarioER: for-loop generating RD & SE results for svm, warning=FALSE, cache=TRUE}
set.seed(42)

# Folder "scenarioER"
for (i in 1:a) {
  closeAllConnections()
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioER/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))

  # found some id != idx
  data$idx <- data$id
  covar.mat <- model.matrix(Y.form, data = data)[,-1]
  
  svmTrainOutcome <- data$outcome
  svmTrainOutcome[svmTrainOutcome == 0] <- -1
  svmTrainPreds <- data.frame(covar.mat)
  
  bounds <- t(data.frame(log2lambda1=c(-10, 10), log2lambda2=c(-10,10)))
  colnames(bounds)<-c("lower", "upper")
  svm.model <- svmfs(x=covar.mat,
                     y = svmTrainOutcome,
                     fs.method = "scad+L2",
                     bounds=bounds,
                     grid.search = "interval",
                     inner.val.method = "cv",
                     show = "none",
                     parms.coding = "none",
                     seed=42)
  
  sel.variables <- colnames(covar.mat)[svm.model$model$fit.info$model.list$model$xind]
  proxy_svm <- proxy.list[proxy.list %in% sel.variables]
  proxyform <- paste0(proxy_svm, collapse = "+")
  rhsform <- paste0(c(covform, proxyform), collapse = "+")
  ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
  W.out_svm <- weightit(ps.formula, 
                          data = data, 
                          estimand = "ATE",
                          method = "ps")  
  
  data$ps.l <- W.out_svm$ps
  data$w.l <- W.out_svm$weights
  
  fit.OR_svm <- glm(out.formula,
                      data = data,
                      weights = W.out_svm$weights,
                      family= binomial(link = "logit"))
  fit.RD_svm <- glm(out.formula,
                       data = data,
                       weights = W.out_svm$weights,
                       family = gaussian(link= "identity"))
  sum.RD_svm <- c(summary(fit.RD_svm)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_svm)[2,2]))
  
  RD_svm[i+a,] <- sum.RD_svm
  rownames(RD_svm)[i+a] <- paste0("ER.data.", i, "_svm")
  num.proxy_svm <- c(num.proxy_svm, length(proxy_svm))
  names(num.proxy_svm)[i+a] <- paste0("ER.data.", i, "_svm")
  
  proxy_svm.i <- paste0("proxy_svm.ER.", i)
  assign(proxy_svm.i, proxy_svm)
  num.proxy_svm.i <- paste0("num.proxy_svm.ER.", i)
  assign(num.proxy_svm.i, length(proxy_svm))
  sum.RD_svm.i <- paste0("sum.RD_svm.ER.", i)
  assign(sum.RD_svm.i, sum.RD_svm)
}
```

```{r scenarioOR: for-loop generating RD & SE results for svm, warning=FALSE, cache=TRUE}
set.seed(42)

# Folder "scenarioOR"
for (i in 1:a) {
  closeAllConnections()
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioOR/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))

  # found some id != idx
  data$idx <- data$id
  covar.mat <- model.matrix(Y.form, data = data)[,-1]
  
  svmTrainOutcome <- data$outcome
  svmTrainOutcome[svmTrainOutcome == 0] <- -1
  svmTrainPreds <- data.frame(covar.mat)
  
  bounds <- t(data.frame(log2lambda1=c(-10, 10), log2lambda2=c(-10,10)))
  colnames(bounds)<-c("lower", "upper")
  svm.model <- svmfs(x=covar.mat,
                     y = svmTrainOutcome,
                     fs.method = "scad+L2",
                     bounds=bounds,
                     grid.search = "interval",
                     inner.val.method = "cv",
                     show = "none",
                     parms.coding = "none",
                     seed=42)
  
  sel.variables <- colnames(covar.mat)[svm.model$model$fit.info$model.list$model$xind]
  proxy_svm <- proxy.list[proxy.list %in% sel.variables]
  proxyform <- paste0(proxy_svm, collapse = "+")
  rhsform <- paste0(c(covform, proxyform), collapse = "+")
  ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
  W.out_svm <- weightit(ps.formula, 
                          data = data, 
                          estimand = "ATE",
                          method = "ps")  
  
  data$ps.l <- W.out_svm$ps
  data$w.l <- W.out_svm$weights
  
  fit.OR_svm <- glm(out.formula,
                      data = data,
                      weights = W.out_svm$weights,
                      family= binomial(link = "logit"))
  fit.RD_svm <- glm(out.formula,
                       data = data,
                       weights = W.out_svm$weights,
                       family = gaussian(link= "identity"))
  sum.RD_svm <- c(summary(fit.RD_svm)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_svm)[2,2]))
  
  RD_svm[i+2*a,] <- sum.RD_svm
  rownames(RD_svm)[i+2*a] <- paste0("OR.data.", i, "_svm")
  num.proxy_svm <- c(num.proxy_svm, length(proxy_svm))
  names(num.proxy_svm)[i+2*a] <- paste0("OR.data.", i, "_svm")
  
  proxy_svm.i <- paste0("proxy_svm.OR.", i)
  assign(proxy_svm.i, proxy_svm)
  num.proxy_svm.i <- paste0("num.proxy_svm.OR.", i)
  assign(num.proxy_svm.i, length(proxy_svm))
  sum.RD_svm.i <- paste0("sum.RD_svm.OR.", i)
  assign(sum.RD_svm.i, sum.RD_svm)
}
```

```{r read RD & SE results by svm, warning=FALSE, cache=TRUE}
RD_svm
```

```{r check number of proxies selected, warning=FALSE, cache=TRUE}
num.proxy_svm
mean(num.proxy_svm[complete.cases(num.proxy_svm)])
```

```{r check intermediate results for each data by svm, warning=FALSE, cache=TRUE}
# check RD & SE by svm for each data, print:
#   sum.RD_svm.n, sum.RD_svm.ER.n, or sum.RD_svm.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
sum.RD_svm.1
sum.RD_svm.ER.2

# check proxy selected by svm for each data, print:
#   proxy_svm.n, proxy_svm.ER.n, or proxy_svm.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
proxy_svm.1
proxy_svm.ER.3

# check number of proxy selected by svm for each data, print:
#   num.proxy_svm.n, num.proxy_svm.ER.n, or num.proxy_svm.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
num.proxy_svm.1
num.proxy_svm.OR.3
```
