---
title: "SimResults_Bross"
author: "Yang Lei"
date: "2024-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(autoCovariateSelection)
require(dplyr)
require(cobalt)
require(WeightIt)
library(tidyverse)
library(ggplot2)
library(lmtest)
library(MASS)
library(Boruta)
library(GA)
library(mclust)
library(penalizedSVM)
library(xgboost)
library(caret)
require(autoCovariateSelection)
library(randomForest)
require(lmtest)
```

```{r load basic information, warning=FALSE, cache=TRUE}}
# global information
exposure <- "obese"
outcome <- "diabetes" 
investigator.specified.covariates <- 
  c(# Demographic
    "age.cat", "sex", "education", "race", 
    "marital", "income", "born", "year",
    
    # health history related variables/access
    "diabetes.family.history", "medical.access",
    
    # behavioral
    "smoking", "diet.healthy", "physical.activity", "sleep",
    
    # Laboratory 
    "uric.acid", "protein.total", "bilirubin.total", "phosphorus",
    "sodium", "potassium", "globulin", "calcium.total", 
    "systolicBP", "diastolicBP", "high.cholesterol"
  )
covform <- paste0(investigator.specified.covariates, collapse = "+")
out.formula <- as.formula(paste0("outcome", "~", "exposure"))
```

```{r change a to load upto 1000 datasets, warning=FALSE, cache=TRUE}}
# change to 1000 later
a <- 8

RD_bross <- data.frame(RD = numeric(),
                       SE = numeric())

errors <- c()
```


```{r scenario: for-loop generating RD & SE results, warning=FALSE, cache=TRUE}}
set.seed(42)

# Folder "scenario"
for (i in 1:a) {
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenario/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))
  
  # found some id != idx
  data$id <- data$idx
  
  # Feature Selection Method 1: Bross Formula
  proxy.df <- data[, c("idx", grep("^rec", names(data), value = TRUE))]
  
  bross.list <- tryCatch({
    get_prioritised_covariates(df = proxy.df,
                               patientIdVarname = "idx", 
                               exposureVector = data$exposure,
                               outcomeVector = data$outcome,
                               patientIdVector = data$idx, 
                               k = 100)
  }, error = function(e) {
    errors <<- c(errors, i)
    "ERROR"
  })
  
  if (class(bross.list) == "character") {
    proxy_bross <- c(NA)
    sum.RD_bross <- c(NA, NA)
    
    RD_bross[i,] <- sum.RD_bross
    rownames(RD_bross)[i] <- paste0("data.", i, "_bross")
    
    proxy_bross.i <- paste0("proxy_bross.", i)
    assign(proxy_bross.i, proxy_bross)
    sum.RD_bross.i <- paste0("sum.RD_bross.", i)
    assign(sum.RD_bross.i, sum.RD_bross)
  } else {
    proxy.df_bross <- bross.list$autoselected_covariate_df
    hdps.data_bross <- merge(data[,c("idx",
                                     outcome, 
                                     exposure, 
                                     investigator.specified.covariates)],
                             proxy.df_bross,
                             by = "idx")
    hdps.data_bross$id <- hdps.data_bross$idx
    hdps.data_bross$idx <- NULL
  
    hdps.data_bross$exposure <- as.numeric(I(hdps.data_bross$obese=='Yes'))
    hdps.data_bross$outcome <- as.numeric(I(hdps.data_bross$diabetes=='Yes'))
  
    proxy_bross <- names(proxy.df_bross[,-1])
    proxyform <- paste0(proxy_bross, collapse = "+")
    rhsformula <- paste0(c(covform, proxyform), collapse = "+")
    ps.formula <- as.formula(paste0("exposure", "~", rhsformula))
  
    W.out_bross <- weightit(ps.formula,
                            data = hdps.data_bross, 
                            estimand = "ATE",
                            method = "ps")
    fit.OR_bross <- glm(out.formula,
                        data = hdps.data_bross,
                        weights = W.out_bross$weights,
                        family= binomial(link = "logit"))
    fit.RD_bross <- glm(out.formula,
                        data= hdps.data_bross,
                        weights= W.out_bross$weights,
                        family=gaussian(link= "identity"))
    sum.RD_bross <- c(summary(fit.RD_bross)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_bross)[2,2]))
  
    RD_bross[i,] <- sum.RD_bross
    rownames(RD_bross)[i] <- paste0("data.", i, "_bross")
  
    proxy_bross.i <- paste0("proxy_bross.", i)
    assign(proxy_bross.i, proxy_bross)
    sum.RD_bross.i <- paste0("sum.RD_bross.", i)
    assign(sum.RD_bross.i, sum.RD_bross)
  }
}
```

```{r scenarioER: for-loop generating RD & SE results, warning=FALSE, cache=TRUE}}
set.seed(42)

# Folder "scenarioER"
for (i in 1:a) {
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioER/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))
  
  # found some id != idx
  data$id <- data$idx
  
  # Feature Selection Method 1: Bross Formula
  proxy.df <- data[, c("idx", grep("^rec", names(data), value = TRUE))]
  
  bross.list <- tryCatch({
    get_prioritised_covariates(df = proxy.df,
                               patientIdVarname = "idx", 
                               exposureVector = data$exposure,
                               outcomeVector = data$outcome,
                               patientIdVector = data$idx, 
                               k = 100)
  }, error = function(e) {
    errors <<- c(errors, paste0("ER.", i))
    "ERROR"
  })
  
  if (class(bross.list) == "character") {
    proxy_bross <- c(NA)
    sum.RD_bross <- c(NA, NA)
    
    RD_bross[i+a,] <- sum.RD_bross
    rownames(RD_bross)[i+a] <- paste0("ER.data.", i, "_bross")
    
    proxy_bross.i <- paste0("proxy_bross.ER.", i)
    assign(proxy_bross.i, proxy_bross)
    sum.RD_bross.i <- paste0("sum.RD_bross.ER.", i)
    assign(sum.RD_bross.i, sum.RD_bross)
  } else {
    proxy.df_bross <- bross.list$autoselected_covariate_df
    hdps.data_bross <- merge(data[,c("idx",
                                     outcome, 
                                     exposure, 
                                     investigator.specified.covariates)],
                             proxy.df_bross,
                             by = "idx")
    hdps.data_bross$id <- hdps.data_bross$idx
    hdps.data_bross$idx <- NULL
  
    hdps.data_bross$exposure <- as.numeric(I(hdps.data_bross$obese=='Yes'))
    hdps.data_bross$outcome <- as.numeric(I(hdps.data_bross$diabetes=='Yes'))
  
    proxy_bross <- names(proxy.df_bross[,-1])
    proxyform <- paste0(proxy_bross, collapse = "+")
    rhsformula <- paste0(c(covform, proxyform), collapse = "+")
    ps.formula <- as.formula(paste0("exposure", "~", rhsformula))
  
    W.out_bross <- weightit(ps.formula,
                            data = hdps.data_bross, 
                            estimand = "ATE",
                            method = "ps")
    fit.OR_bross <- glm(out.formula,
                        data = hdps.data_bross,
                        weights = W.out_bross$weights,
                        family= binomial(link = "logit"))
    fit.RD_bross <- glm(out.formula,
                        data= hdps.data_bross,
                        weights= W.out_bross$weights,
                        family=gaussian(link= "identity"))
    sum.RD_bross <- c(summary(fit.RD_bross)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_bross)[2,2]))
  
    RD_bross[i+a,] <- sum.RD_bross
    rownames(RD_bross)[i+a] <- paste0("ER.data.", i, "_bross")
  
    proxy_bross.i <- paste0("proxy_bross.ER.", i)
    assign(proxy_bross.i, proxy_bross)
    sum.RD_bross.i <- paste0("sum.RD_bross.ER.", i)
    assign(sum.RD_bross.i, sum.RD_bross)
  }
}
```

```{r scenarioOR: for-loop generating RD & SE results, warning=FALSE, cache=TRUE}}
set.seed(42)

# Folder "scenarioOR"
for (i in 1:a) {
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioOR/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))
  
  # found some id != idx
  data$id <- data$idx
  
  # Feature Selection Method 1: Bross Formula
  proxy.df <- data[, c("idx", grep("^rec", names(data), value = TRUE))]
  
  bross.list <- tryCatch({
    get_prioritised_covariates(df = proxy.df,
                               patientIdVarname = "idx", 
                               exposureVector = data$exposure,
                               outcomeVector = data$outcome,
                               patientIdVector = data$idx, 
                               k = 100)
  }, error = function(e) {
    errors <<- c(errors, paste0("OR.", i))
    "ERROR"
  })
  
  if (class(bross.list) == "character") {
    proxy_bross <- c(NA)
    sum.RD_bross <- c(NA, NA)
    
    RD_bross[i+2*a,] <- sum.RD_bross
    rownames(RD_bross)[i+2*a] <- paste0("OR.data.", i, "_bross")
    
    proxy_bross.i <- paste0("proxy_bross.OR.", i)
    assign(proxy_bross.i, proxy_bross)
    sum.RD_bross.i <- paste0("sum.RD_bross.OR.", i)
    assign(sum.RD_bross.i, sum.RD_bross)
  } else {
    proxy.df_bross <- bross.list$autoselected_covariate_df
    hdps.data_bross <- merge(data[,c("idx",
                                     outcome, 
                                     exposure, 
                                     investigator.specified.covariates)],
                             proxy.df_bross,
                             by = "idx")
    hdps.data_bross$id <- hdps.data_bross$idx
    hdps.data_bross$idx <- NULL
  
    hdps.data_bross$exposure <- as.numeric(I(hdps.data_bross$obese=='Yes'))
    hdps.data_bross$outcome <- as.numeric(I(hdps.data_bross$diabetes=='Yes'))
  
    proxy_bross <- names(proxy.df_bross[,-1])
    proxyform <- paste0(proxy_bross, collapse = "+")
    rhsformula <- paste0(c(covform, proxyform), collapse = "+")
    ps.formula <- as.formula(paste0("exposure", "~", rhsformula))
  
    W.out_bross <- weightit(ps.formula,
                            data = hdps.data_bross, 
                            estimand = "ATE",
                            method = "ps")
    fit.OR_bross <- glm(out.formula,
                        data = hdps.data_bross,
                        weights = W.out_bross$weights,
                        family= binomial(link = "logit"))
    fit.RD_bross <- glm(out.formula,
                        data= hdps.data_bross,
                        weights= W.out_bross$weights,
                        family=gaussian(link= "identity"))
    sum.RD_bross <- c(summary(fit.RD_bross)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_bross)[2,2]))
  
    RD_bross[i+2*a,] <- sum.RD_bross
    rownames(RD_bross)[i+2*a] <- paste0("OR.data.", i, "_bross")
  
    proxy_bross.i <- paste0("proxy_bross.OR.", i)
    assign(proxy_bross.i, proxy_bross)
    sum.RD_bross.i <- paste0("sum.RD_bross.OR.", i)
    assign(sum.RD_bross.i, sum.RD_bross)
  }
}
```


```{r read RD & SE results (with error rows), warning=FALSE, cache=TRUE}
RD_bross
```


```{r check index of dataset causing error, warning=FALSE, cache=TRUE}
# check index of dataset causing error
errors
```

```{r read RD & SE results (without error rows), warning=FALSE, cache=TRUE}
RD_bross_no.error <- RD_bross[complete.cases(RD_bross),]
RD_bross_no.error
```

