---
title: "SimResults_Lasso"
author: "Yang Lei"
date: "2024-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(autoCovariateSelection)
require(dplyr)
require(cobalt)
require(WeightIt)
library(tidyverse)
library(ggplot2)
library(lmtest)
library(MASS)
library(Boruta)
library(GA)
library(mclust)
library(penalizedSVM)
library(xgboost)
library(caret)
require(autoCovariateSelection)
library(randomForest)
require(lmtest)
```

```{r load basic information, warning=FALSE, cache=TRUE}}
# global information
exposure <- "obese"
outcome <- "diabetes" 
investigator.specified.covariates <- 
  c(# Demographic
    "age.cat", "sex", "education", "race", 
    "marital", "income", "born", "year",
    
    # health history related variables/access
    "diabetes.family.history", "medical.access",
    
    # behavioral
    "smoking", "diet.healthy", "physical.activity", "sleep",
    
    # Laboratory 
    "uric.acid", "protein.total", "bilirubin.total", "phosphorus",
    "sodium", "potassium", "globulin", "calcium.total", 
    "systolicBP", "diastolicBP", "high.cholesterol"
  )
covform <- paste0(investigator.specified.covariates, collapse = "+")
out.formula <- as.formula(paste0("outcome", "~", "exposure"))

url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenario/data_1.rds")
data <- readRDS(url(url))
proxy.list <- names(data[, c(grep("^rec", names(data), value = TRUE))])
covarsTfull <- c(investigator.specified.covariates, proxy.list)
Y.form <- as.formula(paste0(c("outcome~ exposure", 
                              covarsTfull), collapse = "+") )
```

```{r initialization before for-loop, warning=FALSE, cache=TRUE}}
# 'a' ranges from 1 to 1000 to change the number of datasets loaded in each for-loop
a <- 1000

RD_lasso <- data.frame(RD = numeric(),
                       SE = numeric())
```


```{r}
data <- tryCatch({
  readRDS(url(url))
}, error = function(e) {
  closeAllConnections()
  readRDS(url(url))
})
```


```{r scenario: for-loop generating RD & SE results for lasso, warning=FALSE, cache=TRUE}}
set.seed(42)

# Folder "scenario"
for (i in 1:a) {
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenario/data_", 
                i, 
                ".rds")
  data <- tryCatch({
    readRDS(url(url))
  }, error = function(e) {
    closeAllConnections()
    readRDS(url(url))
  })
  
  # found some id != idx
  data$id <- data$idx
  covar.mat <- model.matrix(Y.form, data = data)[,-1]
  
  lasso.fit <- glmnet::cv.glmnet(y = data$outcome, 
                                 x = covar.mat, 
                                 type.measure='mse',
                                 family="binomial",
                                 alpha = 1, 
                                 nfolds = 5)
  coef.fit <- coef(lasso.fit,s='lambda.min',exact=TRUE)
  sel.variables <- row.names(coef.fit)[which(as.numeric(coef.fit)!=0)]
  proxy_lasso <- proxy.list[proxy.list %in% sel.variables]
  proxyform <- paste0(proxy_lasso, collapse = "+")
  rhsform <- paste0(c(covform, proxyform), collapse = "+")
  ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
  W.out_lasso <- weightit(ps.formula, 
                          data = data, 
                          estimand = "ATE",
                          method = "ps")
  #
  data$ps.l <- W.out_lasso$ps
  data$w.l <- W.out_lasso$weights
  
  fit.OR_lasso <- glm(out.formula,
                      data = data,
                      weights = W.out_lasso$weights,
                      family= binomial(link = "logit"))
  fit.RD_lasso <- glm(out.formula,
                       data = data,
                       weights = W.out_lasso$weights,
                       family = gaussian(link= "identity"))
  sum.RD_lasso <- c(summary(fit.RD_lasso)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_lasso)[2,2]))
  
  RD_lasso[i,] <- sum.RD_lasso
  rownames(RD_lasso)[i] <- paste0("data.", i, "_lasso")
  
  proxy_lasso.i <- paste0("proxy_lasso.", i)
  assign(proxy_lasso.i, proxy_lasso)
  sum.RD_lasso.i <- paste0("sum.RD_lasso.", i)
  assign(sum.RD_lasso.i, sum.RD_lasso)
}
```
```{r scenarioER: for-loop generating RD & SE results for lasso, warning=FALSE, cache=TRUE}}
set.seed(42)

# Folder "scenarioER"
for (i in 1:a) {
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioER/data_", 
                i, 
                ".rds")
  data <- tryCatch({
    readRDS(url(url))
  }, error = function(e) {
    closeAllConnections()
    readRDS(url(url))
  })
  
  # found some id != idx
  data$id <- data$idx
  covar.mat <- model.matrix(Y.form, data = data)[,-1]
  
  lasso.fit <- glmnet::cv.glmnet(y = data$outcome, 
                                 x = covar.mat, 
                                 type.measure='mse',
                                 family="binomial",
                                 alpha = 1, 
                                 nfolds = 5)
  coef.fit <- coef(lasso.fit,s='lambda.min',exact=TRUE)
  sel.variables <- row.names(coef.fit)[which(as.numeric(coef.fit)!=0)]
  proxy_lasso <- proxy.list[proxy.list %in% sel.variables]
  proxyform <- paste0(proxy_lasso, collapse = "+")
  rhsform <- paste0(c(covform, proxyform), collapse = "+")
  ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
  W.out_lasso <- weightit(ps.formula, 
                          data = data, 
                          estimand = "ATE",
                          method = "ps")
  #
  data$ps.l <- W.out_lasso$ps
  data$w.l <- W.out_lasso$weights
  
  fit.OR_lasso <- glm(out.formula,
                      data = data,
                      weights = W.out_lasso$weights,
                      family= binomial(link = "logit"))
  fit.RD_lasso <- glm(out.formula,
                       data = data,
                       weights = W.out_lasso$weights,
                       family = gaussian(link= "identity"))
  sum.RD_lasso <- c(summary(fit.RD_lasso)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_lasso)[2,2]))
  
  RD_lasso[i+a,] <- sum.RD_lasso
  rownames(RD_lasso)[i+a] <- paste0("ER.data.", i, "_lasso")
  
  proxy_lasso.i <- paste0("proxy_lasso.ER.", i)
  assign(proxy_lasso.i, proxy_lasso)
  sum.RD_lasso.i <- paste0("sum.RD_lasso.ER.", i)
  assign(sum.RD_lasso.i, sum.RD_lasso)
}
```
```{r scenarioOR: for-loop generating RD & SE results for lasso, warning=FALSE, cache=TRUE}}
set.seed(42)

# Folder "scenarioOR"
for (i in 1:a) {
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioOR/data_", 
                i, 
                ".rds")
  data <- tryCatch({
    readRDS(url(url))
  }, error = function(e) {
    closeAllConnections()
    readRDS(url(url))
  })
  
  # found some id != idx
  data$id <- data$idx
  covar.mat <- model.matrix(Y.form, data = data)[,-1]
  
  lasso.fit <- glmnet::cv.glmnet(y = data$outcome, 
                                 x = covar.mat, 
                                 type.measure='mse',
                                 family="binomial",
                                 alpha = 1, 
                                 nfolds = 5)
  coef.fit <- coef(lasso.fit,s='lambda.min',exact=TRUE)
  sel.variables <- row.names(coef.fit)[which(as.numeric(coef.fit)!=0)]
  proxy_lasso <- proxy.list[proxy.list %in% sel.variables]
  proxyform <- paste0(proxy_lasso, collapse = "+")
  rhsform <- paste0(c(covform, proxyform), collapse = "+")
  ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
  W.out_lasso <- weightit(ps.formula, 
                          data = data, 
                          estimand = "ATE",
                          method = "ps")
  #
  data$ps.l <- W.out_lasso$ps
  data$w.l <- W.out_lasso$weights
  
  fit.OR_lasso <- glm(out.formula,
                      data = data,
                      weights = W.out_lasso$weights,
                      family= binomial(link = "logit"))
  fit.RD_lasso <- glm(out.formula,
                       data = data,
                       weights = W.out_lasso$weights,
                       family = gaussian(link= "identity"))
  sum.RD_lasso <- c(summary(fit.RD_lasso)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_lasso)[2,2]))
  
  RD_lasso[i+2*a,] <- sum.RD_lasso
  rownames(RD_lasso)[i+2*a] <- paste0("OR.data.", i, "_lasso")
  
  proxy_lasso.i <- paste0("proxy_lasso.OR.", i)
  assign(proxy_lasso.i, proxy_lasso)
  sum.RD_lasso.i <- paste0("sum.RD_lasso.OR.", i)
  assign(sum.RD_lasso.i, sum.RD_lasso)
}
```


```{r read RD & SE results by lasso, warning=FALSE, cache=TRUE}
RD_lasso
```

```{r check intermediate results for each data by lasso, warning=FALSE, cache=TRUE}
# check RD & SE by lasso for each data, print:
#   sum.RD_lasso.n, sum.RD_lasso.ER.n, or sum.RD_lasso.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
sum.RD_lasso.1
sum.RD_lasso.ER.2

# check proxy selected by lasso for each data, print:
#   proxy_lasso.n, proxy_lasso.ER.n, or proxy_lasso.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
proxy_lasso.1
proxy_lasso.ER.3
```

