---
title: "SimResults_Hybrid"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(autoCovariateSelection)
require(dplyr)
require(cobalt)
require(WeightIt)
library(tidyverse)
library(ggplot2)
library(lmtest)
library(MASS)
library(Boruta)
library(GA)
library(mclust)
library(penalizedSVM)
library(xgboost)
library(caret)
require(autoCovariateSelection)
library(randomForest)
require(lmtest)
```

```{r load basic information, warning=FALSE, cache=TRUE}
# global information
exposure <- "obese"
outcome <- "diabetes" 
investigator.specified.covariates <- 
  c(# Demographic
    "age.cat", "sex", "education", "race", 
    "marital", "income", "born", "year",
    
    # health history related variables/access
    "diabetes.family.history", "medical.access",
    
    # behavioral
    "smoking", "diet.healthy", "physical.activity", "sleep",
    
    # Laboratory 
    "uric.acid", "protein.total", "bilirubin.total", "phosphorus",
    "sodium", "potassium", "globulin", "calcium.total", 
    "systolicBP", "diastolicBP", "high.cholesterol"
  )
covform <- paste0(investigator.specified.covariates, collapse = "+")
out.formula <- as.formula(paste0("outcome", "~", "exposure"))
url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenario/data_1.rds")
data <- readRDS(url(url))
proxy.list <- names(data[, c(grep("^rec", names(data), value = TRUE))])
```

```{r initialization before for-loop, warning=FALSE, cache=TRUE}
# 'a' ranges from 1 to 1000 to change the number of datasets loaded in each for-loop
a <- 1000

RD_hybrid <- data.frame(RD = numeric(), SE = numeric())

num.proxy_hybrid <- c()

errors <- c()
```

```{r scenario: for-loop generating RD & SE results, warning=FALSE, cache=TRUE}
set.seed(42)

# Folder "scenario"
for (i in 1:a) {
  closeAllConnections()
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenario/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))
  
  # found some id != idx
  data$idx <- data$id
  
  # Feature Selection Method 1: Bross Formula
  proxy.df <- data[, c("idx", grep("^rec", names(data), value = TRUE))]
  
  hybrid.list <- tryCatch({
    get_prioritised_covariates(df = proxy.df,
                               patientIdVarname = "idx", 
                               exposureVector = data$exposure,
                               outcomeVector = data$outcome,
                               patientIdVector = data$idx, 
                               k = 100)
  }, error = function(e) {
    errors <<- c(errors, i)
    "ERROR"
  })
  
  if (class(hybrid.list) == "character") {
    proxy_hybrid <- c(NA)
    sum.RD_hybrid <- c(NA, NA)
    
    RD_hybrid[i,] <- sum.RD_hybrid
    rownames(RD_hybrid)[i] <- paste0("data.", i, "_hybrid")
    num.proxy_hybrid <- c(num.proxy_hybrid, NA)
    names(num.proxy_hybrid)[i] <- paste0("data.", i, "_hybrid")
    
    proxy_hybrid.i <- paste0("proxy_hybrid.", i)
    assign(proxy_hybrid.i, proxy_hybrid)
    num.proxy_hybrid.i <- paste0("num.proxy_hybrid.", i)
    assign(num.proxy_hybrid.i, NA)
    sum.RD_hybrid.i <- paste0("sum.RD_hybrid.", i)
    assign(sum.RD_hybrid.i, sum.RD_hybrid)
  } else {
    proxy.df_hybrid <- hybrid.list$autoselected_covariate_df
    hdps.data_hybrid <- merge(data[,c("idx",
                                     outcome, 
                                     exposure, 
                                     investigator.specified.covariates)],
                             proxy.df_hybrid,
                             by = "idx")
    hdps.data_hybrid$id <- hdps.data_hybrid$idx
    hdps.data_hybrid$idx <- NULL
  
    hdps.data_hybrid$exposure <- as.numeric(I(hdps.data_hybrid$obese=='Yes'))
    hdps.data_hybrid$outcome <- as.numeric(I(hdps.data_hybrid$diabetes=='Yes'))
  
    proxy_hybrid <- names(proxy.df_hybrid[,-1])
    covarsTfull <- c(investigator.specified.covariates, proxy_hybrid)
    Y.form <- as.formula(paste0(c("outcome~ exposure", covarsTfull), 
                            collapse = "+") )
    covar.mat <- model.matrix(Y.form, data = hdps.data_hybrid)[,-1]
    lasso.fit_hybrid <-glmnet::cv.glmnet(y = hdps.data_hybrid$outcome,
                                         x = covar.mat, 
                                         type.measure='mse',
                                         family="binomial",
                                         alpha = 1, 
                                         nfolds = 5)
    
    coef.fit <- coef(lasso.fit_hybrid,s='lambda.min',exact=TRUE)
    sel.variables <- row.names(coef.fit)[which(as.numeric(coef.fit)!=0)]
    proxy_hybrid <- proxy.list[proxy.list %in% sel.variables]
    proxyform <- paste0(proxy_hybrid, collapse = "+")
    rhsform <- paste0(c(covform, proxyform), collapse = "+")
    ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
    W.out_hybrid <- weightit(ps.formula,
                            data = hdps.data_hybrid, 
                            estimand = "ATE",
                            method = "ps")
    fit.OR_hybrid <- glm(out.formula,
                        data = hdps.data_hybrid,
                        weights = W.out_hybrid$weights,
                        family= binomial(link = "logit"))
    fit.RD_hybrid <- glm(out.formula,
                        data= hdps.data_hybrid,
                        weights= W.out_hybrid$weights,
                        family=gaussian(link= "identity"))
    sum.RD_hybrid <- c(summary(fit.RD_hybrid)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_hybrid)[2,2]))
  
    RD_hybrid[i,] <- sum.RD_hybrid
    rownames(RD_hybrid)[i] <- paste0("data.", i, "_hybrid")
    num.proxy_hybrid <- c(num.proxy_hybrid, length(proxy_hybrid))
    names(num.proxy_hybrid)[i] <- paste0("data.", i, "_hybrid")
  
    proxy_hybrid.i <- paste0("proxy_hybrid.", i)
    assign(proxy_hybrid.i, proxy_hybrid)
    num.proxy_hybrid.i <- paste0("num.proxy_hybrid.", i)
    assign(num.proxy_hybrid.i, length(proxy_hybrid))
    sum.RD_hybrid.i <- paste0("sum.RD_hybrid.", i)
    assign(sum.RD_hybrid.i, sum.RD_hybrid)
  }
}
```

```{r scenarioER: for-loop generating RD & SE results, warning=FALSE, cache=TRUE}
set.seed(42)

# Folder "scenarioER"
for (i in 1:a) {
  closeAllConnections()
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioER/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))
  
  # found some id != idx
  data$idx <- data$id
  
  # Feature Selection Method 1: Bross Formula
  proxy.df <- data[, c("idx", grep("^rec", names(data), value = TRUE))]
  
  hybrid.list <- tryCatch({
    get_prioritised_covariates(df = proxy.df,
                               patientIdVarname = "idx", 
                               exposureVector = data$exposure,
                               outcomeVector = data$outcome,
                               patientIdVector = data$idx, 
                               k = 100)
  }, error = function(e) {
    errors <<- c(errors, paste0("ER.", i))
    "ERROR"
  })
  
  if (class(hybrid.list) == "character") {
    proxy_hybrid <- c(NA)
    sum.RD_hybrid <- c(NA, NA)
    
    RD_hybrid[i+a,] <- sum.RD_hybrid
    rownames(RD_hybrid)[i+a] <- paste0("ER.data.", i, "_hybrid")
    num.proxy_hybrid <- c(num.proxy_hybrid, NA)
    names(num.proxy_hybrid)[i+a] <- paste0("ER.data.", i, "_hybrid")
    
    proxy_hybrid.i <- paste0("proxy_hybrid.ER.", i)
    assign(proxy_hybrid.i, proxy_hybrid)
    num.proxy_hybrid.i <- paste0("num.proxy_hybrid.ER.", i)
    assign(num.proxy_hybrid.i, NA)
    sum.RD_hybrid.i <- paste0("sum.RD_hybrid.ER.", i)
    assign(sum.RD_hybrid.i, sum.RD_hybrid)
  } else {
    proxy.df_hybrid <- hybrid.list$autoselected_covariate_df
    hdps.data_hybrid <- merge(data[,c("idx",
                                     outcome, 
                                     exposure, 
                                     investigator.specified.covariates)],
                             proxy.df_hybrid,
                             by = "idx")
    hdps.data_hybrid$id <- hdps.data_hybrid$idx
    hdps.data_hybrid$idx <- NULL
  
    hdps.data_hybrid$exposure <- as.numeric(I(hdps.data_hybrid$obese=='Yes'))
    hdps.data_hybrid$outcome <- as.numeric(I(hdps.data_hybrid$diabetes=='Yes'))
  
    proxy_hybrid <- names(proxy.df_hybrid[,-1])
    covarsTfull <- c(investigator.specified.covariates, proxy_hybrid)
    Y.form <- as.formula(paste0(c("outcome~ exposure", covarsTfull), 
                            collapse = "+") )
    covar.mat <- model.matrix(Y.form, data = hdps.data_hybrid)[,-1]
    lasso.fit_hybrid <-glmnet::cv.glmnet(y = hdps.data_hybrid$outcome,
                                         x = covar.mat, 
                                         type.measure='mse',
                                         family="binomial",
                                         alpha = 1, 
                                         nfolds = 5)
    
    coef.fit <- coef(lasso.fit_hybrid,s='lambda.min',exact=TRUE)
    sel.variables <- row.names(coef.fit)[which(as.numeric(coef.fit)!=0)]
    proxy_hybrid <- proxy.list[proxy.list %in% sel.variables]
    proxyform <- paste0(proxy_hybrid, collapse = "+")
    rhsform <- paste0(c(covform, proxyform), collapse = "+")
    ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
    W.out_hybrid <- weightit(ps.formula,
                            data = hdps.data_hybrid, 
                            estimand = "ATE",
                            method = "ps")
    fit.OR_hybrid <- glm(out.formula,
                        data = hdps.data_hybrid,
                        weights = W.out_hybrid$weights,
                        family= binomial(link = "logit"))
    fit.RD_hybrid <- glm(out.formula,
                        data= hdps.data_hybrid,
                        weights= W.out_hybrid$weights,
                        family=gaussian(link= "identity"))
    sum.RD_hybrid <- c(summary(fit.RD_hybrid)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_hybrid)[2,2]))
  
    RD_hybrid[i+a,] <- sum.RD_hybrid
    rownames(RD_hybrid)[i+a] <- paste0("ER.data.", i, "_hybrid")
    num.proxy_hybrid <- c(num.proxy_hybrid, length(proxy_hybrid))
    names(num.proxy_hybrid)[i+a] <- paste0("ER.data.", i, "_hybrid")
  
    proxy_hybrid.i <- paste0("proxy_hybrid.ER.", i)
    assign(proxy_hybrid.i, proxy_hybrid)
    num.proxy_hybrid.i <- paste0("num.proxy_hybrid.ER.", i)
    assign(num.proxy_hybrid.i, length(proxy_hybrid))
    sum.RD_hybrid.i <- paste0("sum.RD_hybrid.ER.", i)
    assign(sum.RD_hybrid.i, sum.RD_hybrid)
  }
}
```

```{r scenarioOR: for-loop generating RD & SE results, warning=FALSE, cache=TRUE}
set.seed(42)

# Folder "scenarioOR"
for (i in 1:a) {
  closeAllConnections()
  url <- paste0("https://raw.githubusercontent.com/ehsanx/PlasmodeSim/main/data/hdData/data/scenarioOR/data_", 
                i, 
                ".rds")
  data <- readRDS(url(url))
  
  # found some id != idx
  data$idx <- data$id
  
  # Feature Selection Method 1: Bross Formula
  proxy.df <- data[, c("idx", grep("^rec", names(data), value = TRUE))]
  
  hybrid.list <- tryCatch({
    get_prioritised_covariates(df = proxy.df,
                               patientIdVarname = "idx", 
                               exposureVector = data$exposure,
                               outcomeVector = data$outcome,
                               patientIdVector = data$idx, 
                               k = 100)
  }, error = function(e) {
    errors <<- c(errors, paste0("OR.", i))
    "ERROR"
  })
  
  if (class(hybrid.list) == "character") {
    proxy_hybrid <- c(NA)
    sum.RD_hybrid <- c(NA, NA)
    
    RD_hybrid[i+2*a,] <- sum.RD_hybrid
    rownames(RD_hybrid)[i+2*a] <- paste0("OR.data.", i, "_hybrid")  
    num.proxy_hybrid <- c(num.proxy_hybrid, NA)
    names(num.proxy_hybrid)[i+2*a] <- paste0("OR.data.", i, "_hybrid")
    
    proxy_hybrid.i <- paste0("proxy_hybrid.OR.", i)
    assign(proxy_hybrid.i, proxy_hybrid)
    num.proxy_hybrid.i <- paste0("num.proxy_hybrid.OR.", i)
    assign(num.proxy_hybrid.i, NA)
    sum.RD_hybrid.i <- paste0("sum.RD_hybrid.OR.", i)
    assign(sum.RD_hybrid.i, sum.RD_hybrid)
  } else {
    proxy.df_hybrid <- hybrid.list$autoselected_covariate_df
    hdps.data_hybrid <- merge(data[,c("idx",
                                     outcome, 
                                     exposure, 
                                     investigator.specified.covariates)],
                             proxy.df_hybrid,
                             by = "idx")
    hdps.data_hybrid$id <- hdps.data_hybrid$idx
    hdps.data_hybrid$idx <- NULL
  
    hdps.data_hybrid$exposure <- as.numeric(I(hdps.data_hybrid$obese=='Yes'))
    hdps.data_hybrid$outcome <- as.numeric(I(hdps.data_hybrid$diabetes=='Yes'))
  
    proxy_hybrid <- names(proxy.df_hybrid[,-1])
    covarsTfull <- c(investigator.specified.covariates, proxy_hybrid)
    Y.form <- as.formula(paste0(c("outcome~ exposure", covarsTfull), 
                            collapse = "+") )
    covar.mat <- model.matrix(Y.form, data = hdps.data_hybrid)[,-1]
    lasso.fit_hybrid <-glmnet::cv.glmnet(y = hdps.data_hybrid$outcome,
                                         x = covar.mat, 
                                         type.measure='mse',
                                         family="binomial",
                                         alpha = 1, 
                                         nfolds = 5)
    
    coef.fit <- coef(lasso.fit_hybrid,s='lambda.min',exact=TRUE)
    sel.variables <- row.names(coef.fit)[which(as.numeric(coef.fit)!=0)]
    proxy_hybrid <- proxy.list[proxy.list %in% sel.variables]
    proxyform <- paste0(proxy_hybrid, collapse = "+")
    rhsform <- paste0(c(covform, proxyform), collapse = "+")
    ps.formula <- as.formula(paste0("exposure", "~", rhsform))
  
    W.out_hybrid <- weightit(ps.formula,
                            data = hdps.data_hybrid, 
                            estimand = "ATE",
                            method = "ps")
    fit.OR_hybrid <- glm(out.formula,
                        data = hdps.data_hybrid,
                        weights = W.out_hybrid$weights,
                        family= binomial(link = "logit"))
    fit.RD_hybrid <- glm(out.formula,
                        data= hdps.data_hybrid,
                        weights= W.out_hybrid$weights,
                        family=gaussian(link= "identity"))
    sum.RD_hybrid <- c(summary(fit.RD_hybrid)$coef["exposure", c("Estimate")], sqrt(sandwich::sandwich(fit.RD_hybrid)[2,2]))
  
    RD_hybrid[i+2*a,] <- sum.RD_hybrid
    rownames(RD_hybrid)[i+2*a] <- paste0("OR.data.", i, "_hybrid")
    num.proxy_hybrid <- c(num.proxy_hybrid, length(proxy_hybrid))
    names(num.proxy_hybrid)[i+2*a] <- paste0("OR.data.", i, "_hybrid")
  
    proxy_hybrid.i <- paste0("proxy_hybrid.OR.", i)
    assign(proxy_hybrid.i, proxy_hybrid)
    num.proxy_hybrid.i <- paste0("num.proxy_hybrid.OR.", i)
    assign(num.proxy_hybrid.i, length(proxy_hybrid))
    sum.RD_hybrid.i <- paste0("sum.RD_hybrid.OR.", i)
    assign(sum.RD_hybrid.i, sum.RD_hybrid)
  }
}
```

```{r read RD & SE results (with error rows), warning=FALSE, cache=TRUE}
RD_hybrid
```

```{r check number of proxies selected, warning=FALSE, cache=TRUE}
num.proxy_hybrid
mean(num.proxy_hybrid[complete.cases(num.proxy_hybrid)])
```

```{r check index of dataset causing error, warning=FALSE, cache=TRUE}
# check index of dataset causing error
errors
```

```{r read RD & SE results (without error rows), warning=FALSE, cache=TRUE}
RD_hybrid_no.error <- RD_hybrid[complete.cases(RD_hybrid),]
RD_hybrid_no.error
```

```{r check intermediate results for each data, warning=FALSE, cache=TRUE}
# check RD & SE by hybrid for each data, print:
#   sum.RD_hybrid.n, sum.RD_hybrid.ER.n, or sum.RD_hybrid.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
sum.RD_hybrid.1
sum.RD_hybrid.ER.2

# check proxy selected by hybrid for each data, print:
#   proxy_hybrid.n, proxy_hybrid.ER.n, or proxy_hybrid.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
proxy_hybrid.1
proxy_hybrid.ER.5

# check number of proxy selected by hybrid for each data, print:
#   num.proxy_hybrid.n, num.proxy_hybrid.ER.n, or num.proxy_hybrid.OR.n
#   where "n" is a number ranges from 1 to 1000
#   e.g.
num.proxy_hybrid.1
num.proxy_hybrid.OR.3
```